version: '3.8'

services:
  db:
    container_name: hcg-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - hcg-net

  app:
    container_name: hcg-php
    build:
      args:
        user: webuser
        uid: 1000
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/hcg
    depends_on:
      - db
    networks:
      - hcg-net

  nginx:
    container_name: hcg-nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/hcg
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - hcg-net

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - hcg-net

networks:
  hcg-net:
    driver: bridge